### ISSUE TITLE
"error CS0104: 'Vector3Parameter' is an ambiguous reference" After importing

### ISSUE THREAD

**Issue by Kxrbx** [frostbone25/Unity-Baked-Volumetrics#7]
Here is the different error codes i get right after importing 

Unity version : 2022.3.22.f1 (Latest VRC SDK)

Assets\BakedVolumetrics\Runtime\Scripts\PostProcessing\V1\BakedVolumetricsV1.cs(34,10): error CS0104: 'Vector3Parameter' is an ambiguous reference between 'UnityEngine.Rendering.PostProcessing.Vector3Parameter' and 'UnityEngine.Rendering.Vector3Parameter

Assets\BakedVolumetrics\Runtime\Scripts\PostProcessing\V3\BakedVolumetricsV3.cs(15,16): error CS0104: 'TextureParameter' is an ambiguous reference between 'UnityEngine.Rendering.PostProcessing.TextureParameter' and 'UnityEngine.Rendering.TextureParameter'

Assets\BakedVolumetrics\Runtime\Scripts\PostProcessing\V2\BakedVolumetricsV2.cs(31,10): error CS0104: 'TextureParameter' is an ambiguous reference between 'UnityEngine.Rendering.PostProcessing.TextureParameter' and 'UnityEngine.Rendering.TextureParameter'

Assets\BakedVolumetrics\Runtime\Scripts\PostProcessing\V4\BakedVolumetricsV4.cs(14,16): error CS0104: 'TextureParameter' is an ambiguous reference between 'UnityEngine.Rendering.PostProcessing.TextureParameter' and 'UnityEngine.Rendering.TextureParameter'

**Comment by frostbone25** [comment]
If you are using this only for VRC then to fix those errors you just simply delete the post processing scripts folder. 

Those errors are appearing because the post processing package is not installed in your project (or the API might have changed) but for usage in VRC the post process versions don't get used, only the "Scene Object" version gets used since VRChat does not support custom post process effects.

**Comment by Kxrbx** [comment]
Yeah, I started toying with the project in another Unity project, and figured this might be a conflict issue with some of the modifications the SDK does. 
Thanks for the answer !
